### ISSUE TITLE
Fix for: No free Lisp machines

### ISSUE THREAD

**Issue by larsbrinkhoff** [LM-3/usim#35] opened 2019-04-26 05:36 UTC
It would be nice to have at least one free Lisp machine!

![nolispm](https://user-images.githubusercontent.com/775050/56785536-f1a0b380-67f5-11e9-983c-193775a9d632.png)

**Comment by ams** [comment] 2019-04-26 06:17
Duplicate of https://github.com/LM-3/sys/issues/20 .

**Closed by ams** 2019-04-26 06:17 UTC
