### ISSUE TITLE
Keyboard not working for me

### ISSUE THREAD

**Issue by david-christiansen** [LM-3/usim#16] opened 2018-04-04 13:34 UTC
I was following the quick start instructions and I got usim running. But when it asked for the date and time, keyboard input didn't seem to be reflected on the display. When I pressed any key, the lower right part of the Lisp screen would say "RUN" briefly, but there was no text after the prompt. I also tried typing in the date without being able to see it, but it didn't work for me.

Here's the usim console output:
```
 » ./usim                                                                                                                                                                  06:26:33
CADR emulator v0.9
prom (../bands/promh.mcr.9): code: 1, start: 0, size: 454
[../bands/promh.sym.9] sort 105 symbols (originally 105)
disk: opening disk.img
disk: size: 269562880 bytes
disk: image CHB 1457/23/21
disk: pack label comment '../bands/ucadr.mcr.841'
[../bands/ucadr.sym.841] sort 2502 symbols (originally 2502)
connect_to_server()
chaos: no chaosd server
xbus read 0 400
disk_start_read_compare!
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
connect_to_server()
chaos: no chaosd server
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 111752 requests (109683 known processed) with 0 events remaining.

```
where that last bit is probably due to me closing the usim window.

Any suggestions for troubleshooting or additional information that would be useful? I'm on Ubuntu, running GNOME under X11, if that's relevant.

**Comment by ams** [comment] 2018-04-04 14:49
The easiest way to see if you get any kind of keyboard events is to enable one of the trace points in `usim.h` (e.g., define `traceio` to expand to `printf`) and see what happens.  It will spew out quite a lot of output for all reads/writes to the Unibus, so pipe it to a file and filter out the interesting bits.  I am not sure why it doesn't work, seeing this is simple X11 input handling so this is a curious little bug.  You can also use gdb to put some selected break points and see what is going on (see `x11.c`, `kbd.c`)

Are you using Wayland or something like that perchance?

**Comment by ams** [comment] 2018-04-05 12:39
I’ve tried to reproduce this, but cannot get usim to exhibit the same behavior as you have.  Though, this hasn’t been on any Wayland installation or Ubuntu just very recent versions of X11 and friends.

**Comment by david-christiansen** [comment] 2018-04-05 15:48
I'm certainly not using Wayland, as there's still some compatibility issues with DrRacket that I'm sure I'd have noticed, even though it's usually pretty seamless.

I'll add the suggested printfs and give it a shot when I have a spare hour or so. Thanks!

**Comment by david-christiansen** [comment] 2018-04-05 15:49
Also, I'm pretty sure that some kind of keyboard input is being recognized, because it does say RUN at the bottom when I press a key. There's just no echoed output in the date/time prompt.

**Comment by david-christiansen** [comment] 2018-04-05 15:52
I just tried running inside Xnest and twm in case there was some kind of incompatibility with GNOME shell, and saw the same behavior. Gotta run, but will try again.

**Comment by ams** [comment] 2018-04-05 16:42
This is all curious, can you do a screenshot? Could it be a broken LOD band? Can you dump it somewhere for me to check?

If you can see the RUN lights (prompt and bars) you’ve gotten far enough that the console is up and running. Which means the proper console code is setup and printing, so it should be fine for printing out the time/date prompt, which you aren’t getting at all.

**Comment by david-christiansen** [comment] 2018-04-05 16:44
I'll check when I get home.

But I do get the prompt, I just can't type into it. I press keys, the run
bar says RUN when I press a key, but nothing appears after the prompt.

**Comment by ams** [comment] 2018-04-16 16:37
Any luck reproducing this?

**Comment by ams** [comment] 2018-05-08 17:09
Closing as I have been unable to reproduce and responded.

**Closed by ams** 2018-05-08 17:09 UTC
Labels: bug
